### ISSUE TITLE
Clarification about license terms (non-commercial, no derivatives) needed

### ISSUE THREAD

**Issue by RaphaelWimmer** [propublica/weepeople#2]
I'm wondering about the intended use cases for this nice and useful font.
The CC BY-NC-ND license obviously restricts use of this font for non-commercial uses. As far as I understand, the consensus is that e.g., web sites that contain ads are considered commercial with regard to the CC license. 

a) Use of this font by most other news organizations would therefore not be allowed (or require a separate license), right?
b) Furthermore, use in academic papers which are published by commercial publishers wouldn't be allowed either, right?

The "no derivatives" clause also severely limits use of this font. As far as I understand the definition of "Adaption" in the license, any work that would use glyphs from the font and is not just a simple collection would be forbidden. This would include all images and visualizations using the font. 

c) I assume that it is not really your intention to disallow many sensible uses of this font. Would it be possible to drop the ND restriction or at least explicitly clarify the allowed derivative uses?

**Comment by kleinmatic** [comment]
All good points. Neither is meant to disallow sensible uses of the font:

1) By non-commercial we mean that the font can't be sold. Unfortunately the CC license is intentionally vague about what NC means. Use by other news organizations and use in academic papers would be perfectly acceptable to us.
2) By no derivatives we mean that the shapes themselves can't be altered and new shapes can't be added without permission from us.

Does that make sense? We'll look into adding those specifics to the license page.

**Comment by kleinmatic** [comment]
OK I've added these clarifications to the license.
